import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { JSDOM } from 'jsdom';
import { newCollection } from '../src/library.js';

// Exercise the production renderer's bindings without a display or sockets.
// Browser layout and native modal behavior are covered by test:pose separately.
test('pose viewer binds the selected video, handles queue errors, and cancels a closed submission', async () => {
  const dom = new JSDOM(await readFile('src/renderer/index.html', 'utf8'), { runScripts: 'outside-only', url: 'https://papan.test/' });
  const { window } = dom, document = window.document, $ = id => document.getElementById(id);
  const collection = newCollection('poses'), item1 = randomUUID(), item2 = randomUUID(), image = randomUUID();
  const pin = { id: randomUUID(), title: 'motion album', sourceUrl: 'https://example.com/motion', collectionId: collection.id, coverId: item1,
    items: [{ id: item1, kind: 'video', previewVersion: 1 }, { id: image, kind: 'image' }, { id: item2, kind: 'video', previewVersion: 1 }] };
  const state = { collections: [collection], pins: [pin] }, calls = [], cancelled = [];
  let pending, downloads, fail = true, toolsReady = false;
  window.matchMedia = () => ({ matches: false, addEventListener() {} });
  window.ResizeObserver = window.IntersectionObserver = class { observe() {} unobserve() {} disconnect() {} };
  window.requestAnimationFrame = () => 1; window.cancelAnimationFrame = window.scrollTo = () => {};
  window.HTMLElement.prototype.scrollIntoView = window.HTMLElement.prototype.showPopover = window.HTMLElement.prototype.hidePopover = () => {};
  window.HTMLMediaElement.prototype.pause = window.HTMLMediaElement.prototype.load = () => {};
  window.HTMLMediaElement.prototype.play = async () => {};
  window.HTMLDialogElement.prototype.showModal = function () { this.open = true; };
  window.HTMLDialogElement.prototype.close = function () { this.open = false; this.dispatchEvent(new window.Event('close')); };
  window.papan = { library: async () => structuredClone(state), downloads: async () => [], onDownloads(fn) { downloads = fn; }, onProgress() {},
    openPoseGuide: async () => {}, poseSetup: async () => ({ runtimeBytes: 111000000, modelBytes: 351145849, downloadBytes: toolsReady ? 0 : 462145849, totalBytes: 462145849, platform: 'linux x64' }), cancelDownload: async id => cancelled.push(id),
    enqueuePose: async input => { calls.push(input); if (fail) { fail = false; throw new Error('already queued'); } return new Promise(resolve => { pending = resolve; }); } };
  const flush = () => new Promise(resolve => setImmediate(resolve));
  try {
    window.eval(await readFile('src/renderer/app.js', 'utf8'));
    await flush();
    assert.equal(document.querySelector('.pin-pose').hidden, true, 'card controls stay hidden before tool installation');
    assert.equal(document.querySelector('.pose-indicator').hidden, true);
    state.pins[0].items.push({ id: randomUUID(), kind: 'video', poseFor: item1 });
    downloads([{ id: 'imported-pose', state: 'completed' }]); await flush();
    assert.equal(document.querySelector('.pin-pose').hidden, true, 'an imported pose does not enable controls in an unprepared installation');
    assert.equal(document.querySelector('.pose-indicator').hidden, true);
    state.pins[0].items.pop();
    downloads([{ id: 'removed-import', state: 'completed' }]); await flush();
    document.querySelector('.tile-main').click();
    assert.equal($('pose-controls').hidden, true);
    assert.equal($('extract-pose').hidden, false);
    $('viewer-next').click(); assert.equal($('extract-pose').hidden, true);
    $('viewer-next').click(); $('extract-pose').click(); await flush();
    assert.equal($('pose-port'), null, 'standalone extraction has no server configuration');
    assert.equal($('pose-source').textContent, 'motion album · video 3');
    $('pose-form').dispatchEvent(new window.Event('submit', { cancelable: true })); await flush();
    assert.equal($('pose-status').textContent, 'already queued');
    assert.equal($('start-pose').disabled, false);
    assert.deepEqual(JSON.parse(JSON.stringify(calls[0])), { id: pin.id, itemId: item2 });
    $('pose-form').dispatchEvent(new window.Event('submit', { cancelable: true })); await flush();
    $('pose-dialog').close(); pending('cancel-me'); await flush();
    assert.deepEqual(cancelled, ['cancel-me']);
    assert.equal($('viewer').open, true, 'closing a pending extraction keeps the source viewer');
    $('extract-pose').click(); await flush();
    $('pose-form').dispatchEvent(new window.Event('submit', { cancelable: true })); await flush();
    pending('complete-me'); await flush();
    assert.equal($('viewer').open, false);
    assert.equal($('pose-dialog').open, false);
    downloads([{ id: 'complete-me', kind: 'pose', title: 'Extract pose', state: 'running', progress: 'pose batch 2 of 3' }]);
    assert.ok($('download-list').textContent.includes('pose batch 2 of 3'));
    assert.ok($('download-list').querySelector('[data-action="cancelDownload"]'));
    state.collections[0].protected = true;
    toolsReady = true;
    downloads([{ id: 'complete-me', kind: 'pose', title: 'Extract pose', state: 'completed' }]); await flush();
    assert.equal(document.querySelector('.pin-pose').hidden, false, 'finishing setup reveals card controls without restart');
    assert.equal(document.querySelector('.pin-pose').title, 'extract pose');
    document.querySelector('.tile-main').click();
    assert.equal($('extract-pose').disabled, false, 'unlocked protected collection offers extraction');
    $('extract-pose').click(); await flush();
    assert.equal($('pose-dialog').open, true);
    $('pose-dialog').close();
    $('viewer').close();
    const poseId = randomUUID();
    state.pins[0].items.splice(1, 0, { id: poseId, kind: 'video', poseFor: item1, encrypted: true, previewVersion: 1 });
    downloads([{ id: 'attached-update', state: 'completed' }]); await flush();
    const card = document.querySelector('.pin');
    assert.equal(card._slides.length, 3);
    assert.ok(card._slides.every(item => !item.poseFor));
    assert.equal(card.querySelector('.pin-pose').title, 'view pose');
    assert.equal(card.querySelector('.pose-indicator').hidden, false, 'attachment-only refresh updates the retained card');
    const retainedVideo = card.querySelector('.tile-media video');
    card._index = 1; await window.showSlide(card, false);
    assert.equal(card.querySelector('.pin-pose').hidden, true, 'image slide has no pose action');
    assert.equal(card.querySelector('.pose-indicator').hidden, true);
    card._index = 2; await window.showSlide(card, false);
    assert.equal(card.querySelector('.pin-pose').title, 'extract pose');
    card.querySelector('.pin-pose').click(); await flush();
    assert.equal($('pose-source').textContent, 'motion album · video 3', 'card action targets the displayed album video');
    $('pose-dialog').close(); $('viewer').close();
    card._index = 0; await window.showSlide(card, false);
    assert.equal(card.querySelector('.tile-media video'), retainedVideo, 'updating card controls does not replace its preview');
    card.querySelector('.pin-pose').click(); await flush();
    assert.ok($('viewer-media').querySelector('video').src.includes(poseId), 'card View pose plays the attachment directly');
    $('viewer').close(); document.querySelector('.tile-main').click();
    assert.equal($('extract-pose').textContent, 'view pose');
    assert.equal($('viewer-position').textContent, '1 / 3');
    assert.equal(document.querySelector(`video[src*="${poseId}"]`), null);
    $('extract-pose').click(); await flush();
    assert.equal($('pose-dialog').open, false, 'viewing an attachment needs no setup or extraction');
    assert.ok($('viewer-media').querySelector('video').src.includes(poseId));
    assert.equal($('extract-pose').textContent, 'view original');
    assert.equal($('pose-controls').hidden, false);
    $('pose-person-count').value = '2'; $('pose-confidence').click();
    assert.equal($('pose-person-count').value, '2');
    assert.equal($('pose-confidence').textContent, 'joint confidence: 50%');
    $('reextract-pose').click(); await flush();
    assert.deepEqual(JSON.parse(JSON.stringify(calls.at(-1))), { id: pin.id, itemId: item1, replacePose: true, poseOptions: { personCount: 2, jointConfidence: 0.5 } });
    pending('cleanup-queued'); await flush();
    assert.ok($('pose-cleanup-status').textContent.includes('queued'));
    state.pins[0].items[1].poseTaskId = randomUUID();
    state.pins[0].items[1].poseOptions = { personCount: 2, jointConfidence: 0.7 };
    const beforeCleanupSource = $('viewer-media').querySelector('video').src;
    downloads([{ id: 'cleanup-queued', state: 'completed' }]); await flush();
    assert.equal($('pose-person-count').value, '2');
    assert.equal($('pose-confidence').textContent, 'joint confidence: 70%');
    assert.notEqual($('viewer-media').querySelector('video').src, beforeCleanupSource, 'completed replacement reloads the same pose with a fresh cache key');
    $('extract-pose').click(); assert.equal($('pose-controls').hidden, true);
    $('extract-pose').click(); assert.equal($('pose-confidence').textContent, 'joint confidence: 70%');
    $('viewer-next').click();
    assert.equal($('pose-controls').hidden, true);
    assert.equal($('extract-pose').hidden, true, 'album navigation skips the pose attachment');
    assert.equal($('viewer-position').textContent, '2 / 3');
    $('viewer-prev').click(); $('edit-pin').click();
    assert.equal($('edit-covers').children.length, 3, 'pose cannot be selected as a preview or cover');
    $('pin-editor').close();
    state.collections[0].locked = true; state.pins = [];
    downloads([{ id: 'locked-update', state: 'completed' }]); await flush();
    assert.equal(document.querySelector('.tile-main'), null, 'locked collection exposes no video pin');
  } finally { window.close(); }
});
