import { chromium, expect } from 'playwright/test';
import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { newCollection } from '../src/library.js';
import http from 'node:http';

const collection = newCollection('motion references'), pinId = randomUUID(), video1 = randomUUID(), video2 = randomUUID(), image = randomUUID();
const state = { collections: [collection], pins: [{ id: pinId, collectionId: collection.id, title: 'album movement', sourceUrl: 'https://example.com/album', offline: true, coverId: video1,
  items: [{ id: video1, kind: 'video', previewVersion: 1, previewFile: 'video1.mp4' }, { id: image, kind: 'image' }, { id: video2, kind: 'video', previewVersion: 1, previewFile: 'video2.mp4' }] }] };
const calls = [], errors = [], checks = [];
let browser, fail = true;
const requests = [], videoBytes = await readFile('test/media/portrait.mp4');
const server = http.createServer(async (request, response) => {
  if (request.url.startsWith('/media/')) { requests.push(request.url); response.writeHead(200, { 'content-type': 'video/mp4' }); response.end(videoBytes); return; }
  const file = request.url === '/' ? 'index.html' : request.url.slice(1);
  if (!['index.html', 'app.js', 'styles.css'].includes(file)) { response.writeHead(404); response.end(); return; }
  let body = await readFile(path.join('src/renderer', file));
  if (file === 'app.js') body = body.toString().replace('papan://media/', `${base}/media/`);
  response.writeHead(200, { 'content-type': file.endsWith('.js') ? 'text/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html' }); response.end(body);
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const env = { ...process.env }; delete env.DISPLAY; delete env.WAYLAND_DISPLAY;
try {
  browser = await chromium.launch({ executablePath: process.env.PAPAN_CHROMIUM || '/usr/bin/chromium', headless: true, args: ['--headless', '--ozone-platform=headless', '--enable-automation'], env });
  const cdp = await browser.newBrowserCDPSession(), { arguments: args } = await cdp.send('Browser.getBrowserCommandLine');
  assert.ok(args.some(arg => arg.startsWith('--headless')));
  assert.equal(args.filter(arg => arg.startsWith('--ozone-platform=')).at(-1), '--ozone-platform=headless');
  const page = await browser.newPage({ viewport: { width: 900, height: 800 } }); page.setDefaultTimeout(5000);
  page.on('pageerror', error => errors.push(error.message));
  await page.exposeFunction('poseLibrary', () => structuredClone(state));
  await page.exposeFunction('queuePose', input => { if (fail) { fail = false; throw new Error('This item already has a task.'); } calls.push(input); return randomUUID(); });
  await page.addInitScript(() => {
    window.papan = { library: () => window.poseLibrary(), downloads: async () => [], onDownloads(fn) { window.poseDownloads = fn; }, onProgress() {},
      phoneReceiver: async () => ({ running: false, devices: [], entries: [] }), onPhoneInbox(fn) { window.posePhoneInbox = fn; },
      poseSetup: async () => ({ runtimeBytes: window.poseToolsReady ? 0 : 111000000, modelBytes: window.poseToolsReady ? 0 : 351145849, downloadBytes: window.poseToolsReady ? 0 : 462145849, totalBytes: 462145849, platform: 'linux x64' }), enqueuePose: input => window.queuePose(input), openPoseGuide: async () => {},
      browserSession: async () => 'auto', setBrowserSession: async value => value };
  });
  await page.goto(base);
  await expect(page.locator('.pin-pose')).toBeHidden();
  await expect(page.locator('.pose-indicator')).toBeHidden();
  await page.locator('.tile-main').click();
  await expect(page.locator('#extract-pose')).toBeVisible();
  await page.locator('#viewer-next').click();
  await expect(page.locator('#extract-pose')).toBeHidden();
  await page.locator('#viewer-next').click();
  await page.locator('#extract-pose').click();
  await expect(page.locator('#pose-dialog')).toBeVisible();
  await expect(page.locator('#pose-source')).toHaveText('album movement · video 3');
  await expect(page.locator('#pose-port')).toHaveCount(0);
  await expect(page.locator('#pose-dialog')).toContainText('DWPose');
  await expect(page.locator('#pose-setup')).toContainText('441 MiB');
  await expect(page.locator('#pose-dialog')).toContainText('no ComfyUI or GPU required');
  await expect(page.locator('#pose-dialog details')).not.toHaveAttribute('open');
  await expect(page.locator('#start-pose')).toHaveText('download & extract pose');
  assert.deepEqual(calls, [], 'opening setup does not queue or download dependencies');
  await page.locator('#start-pose').click();
  await expect(page.locator('#pose-status')).toHaveText('This item already has a task.');
  await expect(page.locator('#start-pose')).toBeEnabled();
  await page.locator('#start-pose').click();
  await expect(page.locator('#pose-dialog')).toBeHidden();
  await expect(page.locator('#viewer')).toBeHidden();
  assert.deepEqual(calls, [{ id: pinId, itemId: video2 }]);
  checks.push('video-only button; selected album item; no server configuration; actionable errors; queue submission');
  const taskId = randomUUID();
  await page.evaluate(({ taskId }) => window.poseDownloads([{ id: taskId, title: 'Extract pose · album movement', kind: 'pose', state: 'running', progress: 'pose batch 1 of 3 · extracting poses…' }]), { taskId });
  await page.locator('#downloads-toggle').click();
  await expect(page.locator('#downloads-title')).toHaveText('activity');
  await expect(page.locator('#download-list')).toContainText('pose batch 1 of 3');
  await expect(page.locator('#download-list [data-action="cancelDownload"]')).toBeVisible();
  await page.evaluate(() => window.posePhoneInbox({ running: false, devices: [], entries: [{ id: 'mobile', title: 'https://instagram.com/shared-video', state: 'running', progress: 'downloading item 2 of 3' }] }));
  await expect(page.locator('#download-count')).toHaveText('2');
  await expect(page.locator('#download-list')).toContainText('mobile share');
  await expect(page.locator('#download-list')).toContainText('downloading item 2 of 3');
  await expect(page.locator('#download-list')).toContainText('pose batch 1 of 3');
  await mkdir('artifacts', { recursive: true });
  await page.locator('#downloads-panel').screenshot({ path: 'artifacts/activity-panel.png' });
  await page.evaluate(() => window.posePhoneInbox({ running: false, devices: [], entries: [{ id: 'mobile', title: 'https://instagram.com/shared-video', state: 'saved' }] }));
  await expect(page.locator('#download-count')).toHaveText('1');
  await expect(page.locator('#download-list')).not.toContainText('shared-video');
  checks.push('pose progress and cancellation appear in the existing task panel');
  checks.push('Activity shows simultaneous pose and phone progress; saved shares disappear while receipts stay in receiver settings');
  await page.locator('#downloads-panel').evaluate(panel => panel.hidePopover());
  await page.setViewportSize({ width: 560, height: 400 });
  await page.evaluate(() => { window.poseToolsReady = true; });
  await page.locator('.tile-main').click(); await page.locator('#extract-pose').click();
  await expect(page.locator('#pose-setup')).toHaveText('Ready · no download needed.');
  await expect(page.locator('#pose-dialog details')).not.toHaveAttribute('open');
  await expect(page.locator('#pose-dialog')).toContainText('no ComfyUI or GPU required');
  await page.locator('#start-pose').scrollIntoViewIfNeeded();
  await expect(page.locator('#start-pose')).toBeInViewport();
  assert.equal(await page.locator('#pose-dialog').evaluate(dialog => dialog.scrollWidth > dialog.clientWidth), false);
  await mkdir('artifacts', { recursive: true });
  await page.locator('#pose-dialog').screenshot({ path: 'artifacts/pose-extraction.png' });
  checks.push('short window retains usable controls without horizontal overflow');
  await page.locator('[data-close="pose-dialog"]').first().click();
  await page.locator('[data-close="viewer"]').click();
  state.collections[0].protected = true;
  await page.evaluate(() => window.poseDownloads([{ id: crypto.randomUUID(), title: 'saved', state: 'completed' }]));
  await expect(page.locator('.pin-pose')).toHaveAttribute('title', 'extract pose');
  await page.locator('.tile-main').click();
  await expect(page.locator('#extract-pose')).toBeEnabled();
  await page.locator('#extract-pose').click();
  await expect(page.locator('#pose-dialog')).toContainText('collection protection');
  await page.locator('[data-close="pose-dialog"]').first().click();
  await page.locator('[data-close="viewer"]').click();
  const poseId = randomUUID();
  state.pins[0].items.splice(1, 0, { id: poseId, kind: 'video', poseFor: video1, previewVersion: 1, encrypted: true });
  await page.setViewportSize({ width: 1200, height: 1000 });
  await page.evaluate(() => window.poseDownloads([{ id: crypto.randomUUID(), state: 'completed' }]));
  await expect.poll(() => page.locator('.pin').evaluate(card => card._pin.items.length)).toBe(4);
  await page.locator('.pin').evaluate(async card => { card._index = 0; await window.showSlide(card); });
  await page.locator('.pin').hover();
  await expect(page.locator('.pin-detail')).toHaveCount(0);
  await expect(page.locator('.pin-pose')).toBeVisible();
  await expect(page.locator('.pin-pose')).toHaveAttribute('title', 'view pose');
  await expect(page.locator('.pin-pose')).toHaveAccessibleName('View pose for album movement');
  await expect(page.locator('.pin-pose svg')).toHaveCount(1);
  await expect(page.locator('.pin-pose')).toHaveText('');
  await expect(page.locator('.pose-indicator')).toBeVisible();
  const cardLayout = await page.locator('.pin').evaluate(card => {
    const bounds = card.getBoundingClientRect(), action = card.querySelector('.pin-pose').getBoundingClientRect();
    const source = card.querySelector('.tile-source').getBoundingClientRect(), badge = card.querySelector('.pose-indicator').getBoundingClientRect();
    const style = getComputedStyle(card.querySelector('.pose-indicator'));
    return { actionWidth: action.width, actionHeight: action.height, topInset: action.top - bounds.top, rightInset: bounds.right - action.right,
      sameSourceLine: Math.abs((source.top + source.bottom) / 2 - (badge.top + badge.bottom) / 2) < 1, badgeOnRight: badge.left > source.right,
      background: style.backgroundColor, text: style.color, border: style.borderTopColor, outline: style.outlineColor };
  });
  assert.deepEqual([cardLayout.actionWidth, cardLayout.actionHeight, cardLayout.topInset, cardLayout.rightInset], [29, 25, 9, 9]);
  assert.equal(cardLayout.sameSourceLine && cardLayout.badgeOnRight, true);
  assert.equal(cardLayout.background, 'rgba(0, 0, 0, 0)');
  assert.equal(cardLayout.text, cardLayout.border);
  assert.notEqual(cardLayout.outline, cardLayout.border);
  assert.equal(requests.some(url => url.includes(poseId)), false, 'pose is not fetched by board previews');
  await expect(page.locator('#toast')).toBeHidden();
  await page.locator('.pin').screenshot({ path: 'artifacts/pose-card.png' });
  await page.locator('.pin-pose').click();
  await expect(page.locator('#viewer-media video')).toHaveAttribute('src', new RegExp(poseId));
  await expect(page.locator('#pose-dialog')).toBeHidden();
  await page.locator('[data-close="viewer"]').click();
  checks.push('installed-tools stickman action replaces redundant details button at the same 29×25 size; accessible extraction/playback labels; transparent outlined pose badge; preview opens details');
  assert.equal(await page.locator('.pin').evaluate(card => card._slides.some(item => item.poseFor)), false);
  assert.equal(await page.locator('.pin .tile-media video').getAttribute('src').then(src => src?.includes(poseId)), false, 'pose is neither fetched nor played by board previews');
  await page.locator('.tile-main').click();
  await expect(page.locator('#extract-pose')).toHaveText('view pose');
  await expect(page.locator('#viewer-position')).toHaveText('1 / 3');
  await expect(page.locator('#viewer-media video')).not.toHaveAttribute('src', new RegExp(poseId));
  await page.locator('#extract-pose').click();
  await expect(page.locator('#viewer-media video')).toHaveAttribute('src', new RegExp(poseId));
  await page.waitForFunction(() => document.querySelector('#viewer-media video')?.currentTime > 0.05);
  assert.ok(requests.some(url => url.includes(poseId)), 'explicit view pose loads and plays the attached video');
  await expect(page.locator('#pose-dialog')).toBeHidden();
  await expect(page.locator('#extract-pose')).toHaveText('view original');
  await expect(page.locator('#pose-controls')).toBeVisible();
  await page.locator('#pose-person-count').selectOption('2'); await page.locator('#pose-confidence').click();
  await expect(page.locator('#pose-person-count')).toHaveValue('2');
  await expect(page.locator('#pose-confidence')).toHaveText('joint confidence: 50%');
  await page.locator('#reextract-pose').click();
  await expect(page.locator('#pose-cleanup-status')).toContainText('queued');
  assert.deepEqual(calls.at(-1), { id: pinId, itemId: video1, replacePose: true, poseOptions: { personCount: 2, jointConfidence: 0.5 } });
  assert.equal(await page.locator('#viewer').evaluate(dialog => dialog.scrollWidth > dialog.clientWidth), false);
  await page.locator('#pose-controls').screenshot({ path: 'artifacts/pose-cleanup-controls.png' });
  await page.setViewportSize({ width: 560, height: 400 });
  await page.locator('#reextract-pose').scrollIntoViewIfNeeded(); await expect(page.locator('#reextract-pose')).toBeInViewport();
  assert.equal(await page.locator('#viewer').evaluate(dialog => dialog.scrollWidth > dialog.clientWidth), false);
  await page.setViewportSize({ width: 900, height: 800 });
  state.pins[0].items[1].poseTaskId = randomUUID(); state.pins[0].items[1].poseOptions = { personCount: 2, jointConfidence: 0.7 };
  await page.evaluate(() => window.poseDownloads([{ id: crypto.randomUUID(), state: 'completed' }]));
  await expect(page.locator('#pose-confidence')).toHaveText('joint confidence: 70%');
  await expect(page.locator('#viewer-media video')).toHaveAttribute('src', new RegExp(state.pins[0].items[1].poseTaskId));
  checks.push('pose-only cleanup buttons, original-video payload, confidence presets, short-window layout, and refreshed saved settings');
  await page.locator('#viewer-next').click();
  await expect(page.locator('#pose-controls')).toBeHidden();
  await expect(page.locator('#viewer-position')).toHaveText('2 / 3');
  await expect(page.locator('#extract-pose')).toBeHidden();
  await page.locator('#viewer-prev').click();
  await page.locator('#edit-pin').click();
  await expect(page.locator('#edit-covers .preview-item')).toHaveCount(3);
  await page.locator('[data-close="pin-editor"]').click();
  checks.push('same-pin pose hidden from preview, autoplay, album navigation and cover editing; View pose explicitly loads and plays it');
  state.collections[0].locked = true; state.pins = [];
  await page.evaluate(() => window.poseDownloads([{ id: crypto.randomUUID(), state: 'completed' }]));
  await expect(page.locator('.tile-main')).toHaveCount(0);
  checks.push('unlocked protected video offers extraction; locked collection hides its pins');
  assert.deepEqual(errors, []);
  await writeFile('artifacts/pose-check.json', JSON.stringify({ status: 'passed', display: 'isolated headless Chromium', checks, limits: 'Actual renderer with a stubbed preload. Native IPC and live model inference were not exercised.' }, null, 2) + '\n');
  console.log(JSON.stringify({ checks }, null, 2));
} finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
